COUNTER_ONEWAY1        = 1
COUNTER_ONEWAY2        = 5
COUNTER_ONEWAY3        = 6
COUNTER_ONEWAY4        = 7


COUNTER_TWOWAY1        = 5
COUNTER_TWOWAY2        = 9
COUNTER_TWOWAY3        = 10
COUNTER_TWOWAY4        = 11

COUNTER_ONEWAY_IDS = [COUNTER_ONEWAY1, COUNTER_ONEWAY2, COUNTER_ONEWAY3, COUNTER_ONEWAY4]
COUNTER_TWOWAY_IDS = [COUNTER_TWOWAY1, COUNTER_TWOWAY2, COUNTER_TWOWAY3, COUNTER_TWOWAY4]

HEAT_MAPS          = 2
POLYGON_FILTER     = 4


POLYGON_COUNTER1    = 12
POLYGON_COUNTER2    = 13
POLYGON_COUNTER3    = 14
POLYGON_COUNTER4    = 15

POLYGON_COUNTER_IDS =[POLYGON_COUNTER1, POLYGON_COUNTER2, POLYGON_COUNTER3, POLYGON_COUNTER4]

