# engine
RUN_MODE_THREAD = False
RESIZE_FACTOR = 0.5
DISPLAY_DETECT_FRAME_ONLY = False
DISPLAY_TRACK_INDEX = False
SAVE_VIDEO = True

# detector
DETECT_ENABLE = True
DETECTION_THRESHOLD = 0.1

# tracker
TRACKER_THRESHOLD_DISTANCE = 100  # 90
TRACKER_BUFFER_LENGTH = 100
TRACKER_KEEP_LENGTH = 5
DISTANCE_MARGIN_IN = 20
DISTANCE_MARGIN_OUT = -10
DISTANCE_THRESHOLD = 50
