COUNTER_ONEWAY1        = 1
COUNTER_ONEWAY2        = 2
COUNTER_ONEWAY3        = 3
COUNTER_ONEWAY4        = 4

POLYGON_FILTER     	   = 5



COUNTER_ONEWAY_IDS = [COUNTER_ONEWAY1, COUNTER_ONEWAY2, COUNTER_ONEWAY3, COUNTER_ONEWAY4]

POLYGON_COUNTER_IDS = [11, 12, 13, 14]

